"""Unit tests for compiler provenance gates."""

from dataclasses import dataclass

import pytest

from de_forge.services.compiler_provenance import (
    CompilerProvenanceError,
    CompilerProvenanceService,
)


@dataclass
class RuleStub:
    """Minimal rule object for provenance validation tests."""

    generation_source: str
    detection_ast_id: str | None
    compiled_sigma_id: str | None


def test_manual_draft_rule_fails_compiler_provenance() -> None:
    """Rules not generated by the compiler must be rejected."""
    rule = RuleStub(
        generation_source="manual_draft",
        detection_ast_id="ast-1",
        compiled_sigma_id="sigma-1",
    )

    with pytest.raises(CompilerProvenanceError, match="not compiler-generated"):
        CompilerProvenanceService.assert_rule_has_compiler_provenance(rule)


def test_compiler_rule_missing_detection_ast_fails() -> None:
    """Compiler rules without Detection AST lineage must be rejected."""
    rule = RuleStub(
        generation_source="compiler",
        detection_ast_id=None,
        compiled_sigma_id="sigma-1",
    )

    with pytest.raises(CompilerProvenanceError, match="missing Detection AST provenance"):
        CompilerProvenanceService.assert_rule_has_compiler_provenance(rule)


def test_compiler_rule_missing_compiled_sigma_fails() -> None:
    """Compiler rules without compiled Sigma lineage must be rejected."""
    rule = RuleStub(
        generation_source="compiler",
        detection_ast_id="ast-1",
        compiled_sigma_id=None,
    )

    with pytest.raises(CompilerProvenanceError, match="missing compiled Sigma provenance"):
        CompilerProvenanceService.assert_rule_has_compiler_provenance(rule)


def test_valid_compiler_rule_passes() -> None:
    """Compiler rules with complete provenance must pass."""
    rule = RuleStub(
        generation_source="compiler",
        detection_ast_id="ast-1",
        compiled_sigma_id="sigma-1",
    )

    assert CompilerProvenanceService.assert_rule_has_compiler_provenance(rule) is None
